config/routes.rb
Rails.application.routes.draw do
  root "bookmarks#index"

  resources :bookmarks
  resources :collections do
    member do
      get :bookmarks
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :collection

  def self.search(search)
    where("title LIKE ?", "%#{search}%")
  end
end

app/models/collection.rb
class Collection < ApplicationRecord
  has_many :bookmarks, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  before_action :set_variables

  def set_variables
    @sidebar_collections = Collection.all
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: %i[ show edit update destroy ]

  # GET /bookmarks or /bookmarks.json
  def index
    @bookmarks = Bookmark.search(params[:search])
    @pagy, @bookmarks = pagy(@bookmarks.order("created_at DESC"), items: 12)
  end

  # GET /bookmarks/1 or /bookmarks/1.json
  def show
  end

  # GET /bookmarks/new
  def new
    @bookmark = Bookmark.new
  end

  # GET /bookmarks/1/edit
  def edit
  end

  # POST /bookmarks or /bookmarks.json
  def create
    @bookmark = Bookmark.new(bookmark_params)

    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to bookmark_url(@bookmark), notice: "Bookmark was successfully created." }
        format.json { render :show, status: :created, location: @bookmark }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookmarks/1 or /bookmarks/1.json
  def update
    respond_to do |format|
      if @bookmark.update(bookmark_params)
        format.html { redirect_to bookmark_url(@bookmark), notice: "Bookmark was successfully updated." }
        format.json { render :show, status: :ok, location: @bookmark }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1 or /bookmarks/1.json
  def destroy
    @bookmark.destroy

    respond_to do |format|
      format.html { redirect_to bookmarks_url, notice: "Bookmark was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmark
      @bookmark = Bookmark.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bookmark_params
      params.require(:bookmark).permit(:title, :description, :link, :collection_id, :search)
    end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: %i[ show edit update destroy bookmarks ]

  # GET /collections or /collections.json
  def index
    @count = Collection.all.count
    @pagy, @collections = pagy(Collection.all, items: 10)
  end

  # GET /collections/1 or /collections/1.json
  def show
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections or /collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to collection_url(@collection), notice: "Collection was successfully created." }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1 or /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to collection_url(@collection), notice: "Collection was successfully updated." }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1 or /collections/1.json
  def destroy
    @collection.destroy

    respond_to do |format|
      format.html { redirect_to collections_url, notice: "Collection was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # GET /collections/1/bookmarks
  def bookmarks
    @collection = Collection.find(params[:id])
    @pagy, @collection_bookmarks = pagy(@collection.bookmarks.order("created_at DESC"), items: 12)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def collection_params
      params.require(:collection).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/bookmarks/_bookmark.html.erb
<div class="pt-1 mx-2">
  <div class="mb-4">
    <div class="my-2">
      <h6>
        <i class="bi bi-justify-left align-bottom"></i>
        <span class="px-1">Description</span>
      </h6>
    </div>
    <p>
      <%= bookmark.description %>
    </p>
  </div>

  <div class="mb-4">
    <div>
      <h6>
        <i class="bi bi-link-45deg align-bottom"></i>
        <span class="px-1">Link</span>
      </h6>
    </div>
    <p>
      <a href="<%= bookmark.link %>" target="_blank">
        <%= bookmark.link %>
      </a>
    </p>
  </div>

  <div>
    <div>
      <h6>
        <i class="bi bi-tag align-bottom"></i>
        <span class="px-1">Collection</span>
      </h6>
    </div>
    <p>
      <%= bookmark.collection.name %>
    </p>
  </div>

  <div>
    <div>
      <h6>
        <i class="bi bi-calendar align-bottom"></i>
        <span class="px-1">Created</span>
      </h6>
    </div>
    <p>
      <%= bookmark.created_at.strftime("%Y-%m-%d") %>
    </p>
  </div>
</div>

app/views/bookmarks/_form.html.erb
<%= form_with(model: bookmark) do |form| %>
  <% if bookmark.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>

      <ul>
        <% bookmark.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-4 mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-control", rows: 3 %>
  </div>

  <div class="mb-3">
    <%= form.label :link, class: "form-label" %>
    <%= form.text_field :link, class: "form-control" %>
  </div>

  <div class="col-md-4 mb-3">
    <%= form.label :collection_id, class: "form-label" %>
    <%= form.collection_select :collection_id, Collection.order(:name), :id, :name, {}, class: "form-select" %>
  </div>

  <div class="col-12 py-2">
    <%= form.submit "Save", class: "btn btn-primary px-4" %>
    <%= link_to "Cancel", @bookmark, class: "btn btn-secondary px-3 mx-1" %>
  </div>
<% end %>

app/views/bookmarks/edit.html.erb
<h1 class="mb-4">Editing bookmark</h1>

<%= render "form", bookmark: @bookmark %>

app/views/bookmarks/index.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<div class="d-flex justify-content-between border-bottom mt-1 mb-3">
  <h1>Bookmarks</h1>
  <div class="col-auto">
    <a href="<%= new_bookmark_path %>" class="btn btn-primary mb-3 px-4">New</a>
  </div>
</div>

<p class="mb-4">
  <small>Results: </small>
  <span class="mb-4 rounded-pill px-1">
    <%= @bookmarks.count %>
  </span>
</p>

<div class="h-100">
  <div class="row my-1">
    <% unless @bookmarks.empty? %>
      <% @bookmarks.each do |bookmark| %>
        <div class="col-md-4 mb-4">
          <div class="card shadow">
            <div class="card-body">
              <div class="d-flex justify-content-between mb-2">
                <div class="d-flex">
                  <%= image_tag("bookmark.png", size: "20x20" , class: "mt-1" , alt: "Bookmark icon" ) %>
                  <h5 class="card-title mx-1 truncate">
                    <%= bookmark.title %>
                  </h5>
                </div>
                <%= link_to bookmark_path(bookmark) do %>
                  <i class="bi bi-eye action-icon align-bottom" title="Show"></i>
                <% end %>
              </div>
              <h6 class="card-subtitle mb-2 text-muted truncate">
                <%= bookmark.collection.name %>
              </h6>
              <p class="card-text truncate mt-3 mb-2 pb-2">
                <%= bookmark.description %>
              </p>
              <a href="<%= bookmark.link %>" target="_blank" class="card-link link">
                <%= bookmark.link %>
              </a>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="py-4 my-4 text-center">
        <%= image_tag("bookmarks.png", size: "50x50" , class: "mt-1" , alt: "Bookmarks icon") %>
        <p class="pt-2 pb-2 mb-3 text-muted">No bookmarks.</p>
      </div>
    <% end %>
  </div>
</div>

<footer class="footer mt-auto py-1">
  <div class="container">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</footer>

app/views/bookmarks/new.html.erb
<h1 class="mb-4">New Bookmark</h1>

<%= render "form", bookmark: @bookmark %>

app/views/bookmarks/show.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<div class="mx-2 mb-4 pb-2 border-bottom">
  <div class="d-flex mb-3">
    <%= image_tag("bookmark.png", class: "title-icon align-self-center" , alt: "Bookmark icon" ) %>
    <h1 class="mx-1 mt-1">
      <%= @bookmark.title %>
    </h1>
  </div>
  <div class="d-flex mx-1">
    <div class="">
      <%= link_to edit_bookmark_path(@bookmark), class: "action-icon" do %>
        <i class="bi bi-pencil align-bottom"></i> Edit
      <% end %>
    </div>
    <div class="px-4">
      <%= link_to @bookmark, data: { 'turbo-method': :delete, 'turbo-confirm': 'Are you sure?' }, class: "action-icon" do %>
        <i class="bi bi-trash3 align-bottom"></i> Delete
      <% end %>
    </div>
  </div>
</div>

<%= render @bookmark %>

app/views/collections/_collection.html.erb
<div class="pt-1 mx-2">
  <div class="my-2">
    <div>
      <h6>
        <i class="bi bi-bookmarks align-bottom"></i>
        <span class="px-1">Bookmarks</span>
      </h6>
    </div>
    <p>
      <%= collection.bookmarks.count %>
    </p>
  </div>

  <div>
    <div>
      <h6>
        <i class="bi bi-calendar align-bottom"></i>
        <span class="px-1">Created</span>
      </h6>
    </div>
    <p>
      <%= collection.created_at.strftime("%Y-%m-%d") %>
    </p>
  </div>
</div>

app/views/collections/_form.html.erb
<%= form_with(model: collection) do |form| %>
  <% if collection.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
        <% collection.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-4 mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="col-12 py-2">
    <%= form.submit "Save", class: "btn btn-primary px-4" %>
    <%= link_to "Cancel", @collection, class: "btn btn-secondary px-3 mx-1" %>
  </div>
<% end %>

app/views/collections/bookmarks.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<div class="d-flex justify-content-between mt-1 mb-4 border-bottom">
  <h1><%= @collection.name %></h1>
  <div class="col-auto">
    <a href="<%= new_bookmark_path %>" class="btn btn-primary mb-3 px-4">New</a>
  </div>
</div>

<div class="h-100">
  <div class="row mb-5 pb-5">
    <% unless @collection_bookmarks.empty?  %>
    <% @collection_bookmarks.each do |bookmark| %>
      <div class="col-md-4 mb-4">
        <div class="card shadow">
          <div class="card-body">
            <div class="d-flex justify-content-between mb-2">
              <div class="d-flex">
                <%= image_tag("bookmark.png", size: "20x20" , class: "mt-1" , alt: "Bookmark icon") %>
                <h5 class="card-title mx-1 truncate">
                  <%= bookmark.title %>
                </h5>
              </div>
              <%= link_to bookmark_path(bookmark) do %>
                <i class="bi bi-eye align-bottom action-icon" title="Show"></i>
              <% end %>
            </div>
            <h6 class="card-subtitle mb-2 text-muted truncate">
              <%= bookmark.collection.name %>
            </h6>
            <p class="card-text truncate mt-3 mb-2 pb-2">
              <%= bookmark.description %>
            </p>
            <a href="<%= bookmark.link %>" target="_blank" class="card-link link bottom-0">
              <%= bookmark.link %>
            </a>
          </div>
        </div>
      </div>
    <% end %>
    <% else %>
      <div class="py-4 my-4 text-center">
        <%= image_tag("bookmarks.png", size: "50x50" , class: "" , alt: "Bookmarks icon") %>
        <p class="pt-2 pb-2 mb-3 text-muted">No bookmarks.</p>
      </div>
    <% end %>
  </div>
</div>

<footer class="footer mt-auto">
  <div class="container">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</footer>

app/views/collections/edit.html.erb
<h1 class="mb-4">Editing collection</h1>

<%= render "form", collection: @collection %>

app/views/collections/index.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<div class="d-flex justify-content-between border-bottom mt-1 mb-3">
  <h1>Collections</h1>
  <div class="col-auto">
    <a href="<%= new_collection_path %>" class="btn btn-primary mb-3 px-4">New</a>
  </div>
</div>

<p class="mb-4">
  <small>Total: </small>
  <span class="mb-4 rounded-pill px-1">
    <%= @count %>
  </span>
</p>

<div class="h-100">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Bookmarks</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @collections.each do |collection| %>
        <tr>
          <td><%= image_tag("tag.png", size: "15x15" , alt: "Tag icon") %> <span class="mx-1"><%= collection.name %></td></span>
          <td><%= collection.bookmarks.count %></td>
          <td>
            <a href="<%= collection_path(collection) %>" class="action-icon" title="Show"><i class="bi bi-eye"></i></a>
            <%= link_to edit_collection_path(collection), class: "mx-3 action-icon", title: "Edit" do %>
              <i class="bi bi-pencil align-bottom"></i>
            <% end %>
            <%= link_to collection, data: { 'turbo-method': :delete, 'turbo-confirm': 'Are you sure?' }, class: "action-icon", title: "Delete" do %>
              <i class="bi bi-trash3 align-bottom"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<footer class="footer mt-auto py-3">
  <div class="container">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</footer>

app/views/collections/new.html.erb
<h1 class="mb-4">New collection</h1>

<%= render "form", collection: @collection %>

app/views/collections/show.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<div class="mx-2 mb-4 pb-2 border-bottom">
  <div class="d-flex mb-3">
    <%= image_tag("tag.png", class: "title-icon align-self-center" , alt: "Tag icon" ) %>
    <h1 class="mx-2 mt-1">
      <%= @collection.name %>
    </h1>
  </div>
  <div class="d-flex mx-1">
    <div class="">
      <%= link_to edit_collection_path(@collection), class: "action-icon" do %>
        <i class="bi bi-pencil align-bottom"></i> Edit
      <% end %>
    </div>
    <div class="px-4">
      <%= link_to @collection, data: { 'turbo-method': :delete, 'turbo-confirm': 'Are you sure?' }, class: "action-icon" do %>
        <i class="bi bi-trash3 align-bottom"></i> Delete
      <% end %>
    </div>
  </div>
</div>


<%= render @collection %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-bs-theme="auto">
  <head>
    <title>Keepli</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
  </head>

  <body>
    <%= render "shared/header" %>
    <%= render "shared/sidebar" %>

    <div class="container-fluid">
      <div class="row">
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 mt-4 px-3">
          <%= yield %>
        </main>
      </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_collections.html.erb
<% @sidebar_collections.each do |collection| %>
  <ul class="nav flex-column nav-pills">
    <li class="nav-item sidebar-collection">
      <%= link_to bookmarks_collection_path(collection), class: class_names("nav-link", "text-decoration-none", { active: current_page?(bookmarks_collection_path(collection)) }) do %>
        <div class="d-flex justify-content-between align-items-center px-2">
          <span class="tag"><%= collection.name %></span>
          <span class="badge text-bg-dark rounded-pill align-text-bottom"><%= collection.bookmarks.count %></span>
        </div>
      <% end %>
    </li>
  </ul>
<% end %>

app/views/shared/_header.html.erb
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6 bg-dark" href="<%= root_path %>">Keepli</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="py-4"></div>
  <%= form_tag(bookmarks_path, method: "get", class: "w-100 mx-4") do %>
    <%= text_field_tag(:search, params[:search], class: "form-control form-control-dark my-2", placeholder: "Search bookmarks") %>
  <% end %>
</header>

app/views/shared/_sidebar.html.erb
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block sidebar bg-light collapse mt-4 mb-3">
  <div class="position-sticky sidebar-sticky px-1 pt-4">
    <ul class="nav nav-pills flex-column sticky-top border-bottom pb-2 mb-3">
      <li class="nav-item">
        <%= link_to bookmarks_path, class: class_names("nav-link", "teste", { active: current_page?(bookmarks_path) || current_page?(root_path) }) do %>
          <i class="bi bi-bookmark align-bottom px-1"></i><span class="text-decoration-none fw-light">Bookmarks</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to collections_path, class: class_names("nav-link", "teste", { active: current_page?(collections_path) }) do %>
          <i class="bi bi-grid align-bottom px-1"></i><span class="text-decoration-none fw-light">Collections</span>
        <% end %>
      </li>
    </ul>
    <%= render "shared/collections", collections: @collections %>
  </div>
</nav>